export const postTitles = [
  "A Day in My Life as a Web Dev",
  "Why I Love Early Morning Coffee",
  "What I've Learned Teaching Code",
  "Struggles of Balancing Freelance and Full-Time",
  "The Best Advice I Ever Received",
  "How I Got into Programming",
  "The Project That Changed Everything",
  "Why I Prefer Night Coding Sessions",
  "Challenges of Building My Own App",
  "The Importance of Taking Breaks",
  "Why I Started Blogging About Code",
  "My Go-To Productivity Hacks",
  "Lessons From My First Freelance Gig",
  "How I Handle Imposter Syndrome",
  "The Tech That Excites Me Most in 2024",
  "Why Mentorship Is So Important",
  "How Coding Changed My Problem-Solving Skills",
  "The Joys (and Frustrations) of Debugging",
  "Finding Inspiration Outside of Code",
  "My Favorite Tools for Staying Organized",
  "My Journey From Novice to Web Dev",
  "How I Manage Burnout as a Developer",
  "Why Continuous Learning is Key in Tech",
  "The One Tool I Can’t Live Without",
  "Building My First App: What I Wish I Knew",
  "How I Deal with Creative Block",
  "The Most Exciting Part of Teaching Code",
  "Balancing Tech Trends with Core Skills",
  "How I Stay Motivated During Long Projects",
  "The Best Mistake I Ever Made in Coding",
  "How I Organize My Day as a Developer",
  "The First Line of Code I Ever Wrote",
  "Why Collaboration is Key in Development",
  "How I Stay Up to Date with Tech Trends",
  "The Most Challenging Project I've Worked On",
  "Finding Balance Between Work and Life",
  "Why I Started Freelancing",
  "How I Approach Learning New Technologies",
  "The Moment I Knew I Wanted to Teach Code",
  "The Role of Creativity in Web Development",
  "How I Handle Feedback on My Code",
  "Why I Started Working on Side Projects",
  "The Joy of Seeing a Project Go Live",
  "My Favorite Programming Languages and Why",
  "How Teaching Has Made Me a Better Developer",
  "The Biggest Lesson I’ve Learned From Freelancing",
  "How I Overcame My Fear of Public Speaking",
  "The Importance of Clean Code",
  "Why Consistency Beats Perfection in Coding",
  "What I Do When I Feel Stuck on a Problem",
];

export const postBodies = [
  "Today was packed with meetings, debugging sessions, and a lot of coffee! Here's how it went...",
  "Mornings are my sacred time. Coffee in hand, I feel like I can take on the world.",
  "Teaching coding has taught me a lot—about patience, creativity, and the art of explaining complex ideas simply.",
  "Balancing freelance projects and my full-time teaching gig isn't easy, but it's definitely rewarding.",
  "The best advice I ever got was to focus on solving problems, not just writing code.",
  "I started coding because I was curious about how websites worked. Little did I know, it would become my career!",
  "There was one project that pushed me to my limits but made me a better developer. Here's the story.",
  "There's something about coding at night. The world is quiet, and I feel super focused.",
  "Building my own app has been both challenging and exciting. The ups and downs are real, though.",
  "I've realized how important it is to step away from the screen and recharge, especially during long coding sessions.",
  "I've always loved sharing knowledge. Starting a blog felt like the next natural step in my journey.",
  "To stay productive, I rely on time-blocking, the Pomodoro technique, and a strict to-do list.",
  "My first freelance project was a whirlwind of challenges and growth. Here's what I learned.",
  "Imposter syndrome is real, even for experienced devs. Here's how I work through it when it hits.",
  "AI, Web3, and serverless architecture are just a few of the technologies I'm most excited about this year.",
  "Having a mentor has been invaluable for my career. It’s amazing how much you can learn from someone else's experience.",
  "Coding has completely changed the way I approach problems—breaking them down into small, manageable tasks.",
  "Debugging can be frustrating, but there’s no better feeling than finally solving the problem.",
  "Sometimes, the best coding ideas come from non-tech activities like reading or going for a walk.",
  "Staying organized is key. I use tools like Trello, Notion, and good old-fashioned sticky notes to keep everything on track.",
  "Looking back, it's crazy how much I've grown since I first started coding. Here's my story from novice to now.",
  "Burnout is real, especially in tech. Here are some of the ways I manage it and find balance.",
  "In the fast-changing world of tech, staying curious and learning new things is essential to staying relevant.",
  "I can’t imagine my workflow without my favorite tool: VS Code. It’s a lifesaver for productivity.",
  "Building my first app was an eye-opener. If I could go back, here are some tips I’d give my past self.",
  "Creative blocks happen, even in coding. When I hit one, here’s how I reboot my creativity.",
  "The best part of teaching code is seeing students finally 'get it' after struggling with a concept.",
  "It’s easy to get distracted by trends, but staying focused on the fundamentals is just as important.",
  "Long projects can feel draining, but breaking them into smaller milestones helps me stay motivated.",
  "Once, I made a huge mistake in my code that actually led to discovering a better solution. Here's what happened.",
  "As a developer, managing time can be tricky. Here’s how I structure my day to stay productive.",
  "I'll never forget the first line of code I wrote—it sparked a passion I didn’t know I had.",
  "Collaboration is at the heart of any good development team. Here's why it’s so important.",
  "Keeping up with tech trends can be overwhelming, but I’ve developed a few strategies that help me stay on top.",
  "The most challenging project I’ve worked on pushed me to my limits, but I came out stronger on the other side.",
  "Balancing work and life can be tough as a developer. Here's how I try to maintain that balance.",
  "Freelancing gave me the freedom I wanted, but it also came with its own set of challenges.",
  "When learning new technologies, I always focus on breaking down complex concepts into smaller, actionable steps.",
  "I realized I wanted to teach code when I helped a friend debug their project—it was such a rewarding experience.",
  "Creativity plays a big role in web development. It’s not just about code, but also about solving problems in new ways.",
  "Getting feedback on your code can be tough, but it's one of the best ways to grow. Here’s how I handle it.",
  "Side projects have been a huge source of learning for me. Here’s why I believe every dev should work on one.",
  "Nothing beats the feeling of seeing a project you've worked hard on finally go live. It's such a rewarding moment.",
  "I've worked with several programming languages, but a few stand out as my favorites. Here’s why I love them.",
  "Teaching others has made me rethink my approach to coding, and in the process, it’s helped me improve my own skills.",
  "Freelancing has taught me many lessons, but the biggest one is to always set clear expectations from the start.",
  "Public speaking used to scare me, but over time, I’ve learned how to overcome that fear and even enjoy it.",
  "Writing clean code isn’t just about aesthetics—it's about making sure your code is understandable and maintainable.",
  "In coding, consistency is more important than chasing perfection. Here’s why steady progress trumps flawless execution.",
  "When I feel stuck on a problem, I step away, clear my mind, and come back with a fresh perspective. It always helps.",
];
